"""change relation users_invites

Revision ID: 0532e3790595
Revises: 3b98637b1654
Create Date: 2024-03-29 20:15:24.406676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0532e3790595'
down_revision: Union[str, None] = '3b98637b1654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'invites', ['invite_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invite_id')
    # ### end Alembic commands ###