"""add dni field

Revision ID: 2cfd125b4fd0
Revises: 0532e3790595
Create Date: 2024-03-29 20:28:44.664493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cfd125b4fd0'
down_revision: Union[str, None] = '0532e3790595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('dni', sa.Integer(), nullable=False))
    op.drop_constraint('invites_user_id_fkey', 'invites', type_='foreignkey')
    op.drop_column('invites', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('invites_user_id_fkey', 'invites', 'users', ['user_id'], ['id'])
    op.drop_column('invites', 'dni')
    # ### end Alembic commands ###