"""add column resourse_type in post table

Revision ID: 86e5e8636128
Revises: 45ad82c1160e
Create Date: 2024-04-04 15:56:09.820651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86e5e8636128'
down_revision: Union[str, None] = '45ad82c1160e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('IMAGE', 'VIDEO', name='mediatype').create(op.get_bind())
    op.add_column('posts', sa.Column('resourse_type', postgresql.ENUM('IMAGE', 'VIDEO', name='mediatype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'resourse_type')
    sa.Enum('IMAGE', 'VIDEO', name='mediatype').drop(op.get_bind())
    # ### end Alembic commands ###