"""add otp field

Revision ID: caa0bb35fbe6
Revises: 86e5e8636128
Create Date: 2024-04-14 23:09:06.105027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'caa0bb35fbe6'
down_revision: Union[str, None] = '86e5e8636128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('otp_code', sa.Integer(), nullable=True))
    op.add_column('invites', sa.Column('otp_expired', sa.Boolean(), nullable=True))
    op.drop_constraint('invites_dni_key', 'invites', type_='unique')
    op.drop_column('invites', 'dni')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('dni', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('invites_dni_key', 'invites', ['dni'])
    op.drop_column('invites', 'otp_expired')
    op.drop_column('invites', 'otp_code')
    # ### end Alembic commands ###